config/routes.rb
Entv::Application.routes.draw do
  root "static#index"
  resources :products, only: [:show, :index]
  resources :order_items, only: [:create, :index]
  resources :orders, only: [:create, :index, :new]
  delete 'order_items' => 'order_items#destroy', as: :delete_order_item
  patch 'order_items' => 'order_items#update', as: :update_order_item
  get "about" => "static#about", as: :about
  get "contact" => "static#contact", as: :contact

  devise_for :users
  devise_scope :user do
    get "sign_in" => "devise/sessions#new", as: :sign_in
    get "sign_out" => "devise/sessions#destroy", as: :sign_out
    get "sign_up" => "devise/registrations#new", as: :sign_up
    get "profile" => "devise/registrations#edit", as: :profile
    get "reset_password" => "devise/passwords#new", as: :reset_password
  end

  devise_for :admins
  devise_scope :admins do
    get "admins/sign_in" => "devise/sessions#new", as: :admin_sign_in
    get "admins/sign_out" => "devise/sessions#destroy", as: :admin_sign_out
  end
  
  namespace :admin do
    root "products#index"
    
    resources :products
    resources :orders, only: [:index, :show, :update]
    resources :users, only: [:index, :destroy]
    resources :categories, except: [:show, :destroy]
    resources :imports, except: [:edit, :update, :destroy]
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products  
  validates_presence_of :name
  validates_uniqueness_of :name
  validates_presence_of :description
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController 
  before_action :authenticate_admin!
  before_action :set_category, only: [:edit, :update]
  
  def index
    @categories = Category.all
  end
  
  def new
    @category = Category.new
    session[:referer] = request.referer if request.referer == new_admin_product_url
  end
  
  def create
    @category = Category.new category_params
    if @category.save
      flash[:success] = "A new category has been added."
      redirect_back_or_to admin_categories_path
    else
      render "new"
    end
  end
  
  def edit
  end
  
  def update
    if @category.update_attributes category_params
      flash[:success] = "Successfully updated."
      redirect_to admin_categories_path
    else
      render "edit"
    end
  end
  
  private
  
    def category_params
      params.require(:category).permit(:name, :description)
    end
  
    def set_category
      @category = Category.find params[:id]
    end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/views/admin/categories/_category.html.erb
<tr>
  <td><%= category.id %></td>
  <td><%= category.name %></td>
  <td><%= truncate category.description, length: 35 %></td>
  <td><%= link_to "Edit", edit_admin_category_path(category) %></td>
</tr>

app/views/admin/categories/_form.html.erb
<div class="col-sm-6 col-sm-offset-3 form-wrapper">
  <h2><%= title %></h2>

  <ol class="breadcrumb">
    <li><%= link_to "Back", admin_categories_path %></li>
    <li class="active"><%= @category.new_record? ? "New" : "Edit" %></li>
  </ol>

  <%= render "share/error_messages", errors: @category.errors %>

  <%= form_for [:admin, @category], html: { class: "form" } do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.submit class: "btn btn-primary form-control" %>
    </div>
  <% end %>
</div>

app/views/admin/categories/edit.html.erb
<%= render "form", title: "Edit Category" %>

app/views/admin/categories/index.html.erb
<div class="form-wrapper">
  <h2>Products List</h2><br />

  <table class="table table-condensed table-bordered">
    <tr>
      <th>#</th>
      <th>Name</th>
      <th>Description</th>
      <th>More</th>
    </tr>
    <%= render @categories %>
  </table>
  <p><%= link_to "New Category", new_admin_category_path %></p>
</div>

app/views/admin/categories/new.html.erb
<%= render "form", title: "New Category" %>