config/routes.rb
Entv::Application.routes.draw do
  root "static#index"
  resources :products, only: [:show, :index]
  resources :order_items, only: [:create, :index]
  resources :orders, only: [:create, :index, :new]
  delete 'order_items' => 'order_items#destroy', as: :delete_order_item
  patch 'order_items' => 'order_items#update', as: :update_order_item
  get "about" => "static#about", as: :about
  get "contact" => "static#contact", as: :contact

  devise_for :users
  devise_scope :user do
    get "sign_in" => "devise/sessions#new", as: :sign_in
    get "sign_out" => "devise/sessions#destroy", as: :sign_out
    get "sign_up" => "devise/registrations#new", as: :sign_up
    get "profile" => "devise/registrations#edit", as: :profile
    get "reset_password" => "devise/passwords#new", as: :reset_password
  end

  devise_for :admins
  devise_scope :admins do
    get "admins/sign_in" => "devise/sessions#new", as: :admin_sign_in
    get "admins/sign_out" => "devise/sessions#destroy", as: :admin_sign_out
  end
  
  namespace :admin do
    root "products#index"
    
    resources :products
    resources :orders, only: [:index, :show, :update]
    resources :users, only: [:index, :destroy]
    resources :categories, except: [:show, :destroy]
    resources :imports, except: [:edit, :update, :destroy]
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  has_one :spec, dependent: :destroy, inverse_of: :product
  has_many :import_products
  has_many :imports, through: :import_products, source: :import

  accepts_nested_attributes_for :spec
  mount_uploader :picture, PictureUploader

  validates_associated :category
  validates_presence_of :name
  validates_uniqueness_of :name
  validates_presence_of :price
  validates_numericality_of :price
  validates_presence_of :company
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all
  end

  def show
  end

  def new
    @product = Product.new
    session[:referer] = request.referer if request.referer == new_admin_import_url
  end

  def create
    @product = Product.new product_params
    if @product.save
      flash[:success] = "A new product has been added."
      redirect_back_or_to admin_products_path
    else
      flash.now[:danger] = "Error while processing data."
      render "new"
    end
  end

  def edit
  end

  def update
    if @product.update_attributes product_params
      flash[:success] = "Product's information has been updated."
      redirect_to admin_products_path
    else
      flash.now[:danger] = "Error while processing data."
      render "edit"
    end
  end

  def destroy
    @product.destroy
    flash[:success] = "Successfully remove a product."
    redirect_to admin_products_path
  end

  private

    def product_params
      params.require(:product).permit(:category_id, :name, :company, :price, :picture,
        :remote_picture_url, spec_attributes: [:cpu, :ram, :os, :storage, :screen_size, :vga, :battery])
    end

    def set_product
      @product = Product.find params[:id]
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    if params[:category_id].blank? && params[:company].blank?
      @products = Product.all
    elsif params[:category_id]
      category = Category.find params[:category_id]
      @products = category.products.where "company LIKE ?", "#{params[:company]}%"
    else
      @products = Product.where(company: params[:company])
    end
  end
  
  def show
    @categories = Category.all
    @product = Product.find(params[:id])
    @s = Spec.find_by(product: @product)
    session[:cart] = Hash.new(0) if session[:cart].nil?    
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def format_in_stock(product)
    if product.total.nil? || product.total.zero?
      "Out of Stock"
    else
      pluralize(product.total, "Item") + " In Stock"      
    end
  end
end

app/views/admin/products/_form.html.erb
<div class="col-sm-6 col-sm-offset-3 form-wrapper">
  <h2><%= title %></h2>
  
  <ol class="breadcrumb">
    <li><%= link_to "Back", admin_products_path %></li>
    <li class="active"><%= @product.new_record? ? "New" : "Edit" %></li>
  </ol>

  <%= render "share/error_messages", errors: @product.errors %>

  <%= form_for [:admin, @product], html: { class: "form", multipart: true } do |f| %>
    <div class="form-group">
      <%= f.label :category %> or 
      <%= link_to "New Category", new_admin_category_path %>
      <%= f.collection_select :category_id, Category.all,
      :id, :name, {}, { class: "form-control" } %>
    </div>

    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :price %>
      <%= f.text_field :price, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :company %>
      <%= f.text_field :company, class: "form-control" %>
    </div>
    
    <div class="form-group">
      <%= f.file_field :picture %>
    </div>
    
    <div class="form-group">
      <%= f.label :remote_picture_url, "Or image url" %>
      <%= f.text_field :remote_picture_url, class: "form-control" %>
    </div> 
    
    <div style="display: none;" class="form-group">
      <hr />
      <%= f.fields_for :spec, @product.spec ? @product.spec : @product.build_spec do |builder| %>
        <%= render "spec", f: builder %>
      <% end %>
    </div>
    <a id="show_spec" href="#" style="display: block; margin-bottom: 10px;">Show Detail</a>

    <div class="form-group">
      <%= f.submit class: "btn btn-primary form-control" %>
    </div>
  <% end %>
</div>

<script type="text/javascript">
  $("#show_spec").on("click", function(event) {
    event.preventDefault();
    if ($(this).prev().css("display") == "none") {
      $(this).text("Hide Detail");
    } else {
      $(this).text("Show Detail");
    }
    $(this).prev().toggle("fast");
  });
</script>

app/views/admin/products/_product.html.erb
<tr>
  <td><%= product.id %></td>
  <td><%= truncate product.name, length: 25 %></td>
  <td><%= number_to_currency product.price, unit: "$" %></td>
  <td><%= product.total %></td>
  <td class="breadcrumb">
    <li><%= link_to "Detail", [:admin, product] %></li>
    <li><%= link_to "Edit", edit_admin_product_path(product) %></li>
    <li><%= link_to "Remove", [:admin, product], data: { method: :delete, confirm: "Do you want to remove this product" } %></li>
  </td>
</tr>

app/views/admin/products/_spec.html.erb
<%= f.label :cpu %>
<%= f.text_field :cpu, class: "form-control" %>
<%= f.label :ram %>
<%= f.text_field :ram, class: "form-control" %>
<%= f.label :vga %>
<%= f.text_field :vga, class: "form-control" %>
<%= f.label :os %>
<%= f.text_field :os, class: "form-control" %>
<%= f.label :storage %>
<%= f.text_field :storage, class: "form-control" %>
<%= f.label :screen_size %>
<%= f.text_field :screen_size, class: "form-control" %>
<%= f.label :battery %>
<%= f.text_field :battery, class: "form-control" %>

app/views/admin/products/edit.html.erb
<%= render "form", title: "Edit Product" %>

app/views/admin/products/index.html.erb
<div class="form-wrapper">
  <h2>Products List</h2><br />

  <table class="table table-condensed table-bordered">
    <tr>
      <th>#</th>
      <th>Name</th>
      <th>Price</th>
      <th>Stock</th>
      <th>More</th>
    </tr>
    <%= render @products %>
  </table>
  <p><%= link_to "New Product", new_admin_product_path %></p>
</div>

app/views/admin/products/new.html.erb
<%= render "form", title: "New Product" %>

app/views/admin/products/show.html.erb
<div class="form-wrapper product">
  <div>
    <h2>Product</h2>
    
    <%= image_tag @product.picture_url(:big_thumb) %>
    <p><label>Name: </label><%= @product.name %></p>
    <p><label>Price: </label><%= number_to_currency @product.price, unit: "$" %></p>
    <p><label>Company: </label><%= @product.company ? @product.company : "NA" %></p>
    <p><label>Available in stock: </label><%= @product.total %></p>
    <p>
      <label>Spec: </label>
      <% if @product.spec %>
        <% spec = @product.spec %>
        <label>CPU: </label><%= spec.cpu ? spec.cpu : "NA" %>, 
        <label>RAM: </label><%= spec.ram ? spec.ram : "NA" %>, 
        <label>VGA: </label><%= spec.vga ? spec.vga : "NA" %>, 
        <label>Operating System:</label><%= spec.os ? spec.os : "NA" %>, 
        <label>Storage: </label><%= spec.storage ? spec.storage : "NA" %>, 
        <label>Screen: </label><%= spec.screen_size ? spec.screen_size : "NA" %>, 
        <label>Battery; </label><%= spec.battery ? spec.battery : "NA" %>
      <% else %>
        Not available
      <% end %>
    </p>
  </div>
</div>