config/routes.rb
Entv::Application.routes.draw do
  root "static#index"
  resources :products, only: [:show, :index]
  resources :order_items, only: [:create, :index]
  resources :orders, only: [:create, :index, :new]
  delete 'order_items' => 'order_items#destroy', as: :delete_order_item
  patch 'order_items' => 'order_items#update', as: :update_order_item
  get "about" => "static#about", as: :about
  get "contact" => "static#contact", as: :contact

  devise_for :users
  devise_scope :user do
    get "sign_in" => "devise/sessions#new", as: :sign_in
    get "sign_out" => "devise/sessions#destroy", as: :sign_out
    get "sign_up" => "devise/registrations#new", as: :sign_up
    get "profile" => "devise/registrations#edit", as: :profile
    get "reset_password" => "devise/passwords#new", as: :reset_password
  end

  devise_for :admins
  devise_scope :admins do
    get "admins/sign_in" => "devise/sessions#new", as: :admin_sign_in
    get "admins/sign_out" => "devise/sessions#destroy", as: :admin_sign_out
  end
  
  namespace :admin do
    root "products#index"
    
    resources :products
    resources :orders, only: [:index, :show, :update]
    resources :users, only: [:index, :destroy]
    resources :categories, except: [:show, :destroy]
    resources :imports, except: [:edit, :update, :destroy]
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  has_one :spec, dependent: :destroy, inverse_of: :product
  has_many :import_products
  has_many :imports, through: :import_products, source: :import

  accepts_nested_attributes_for :spec
  mount_uploader :picture, PictureUploader

  validates_associated :category
  validates_presence_of :name
  validates_uniqueness_of :name
  validates_presence_of :price
  validates_numericality_of :price
  validates_presence_of :company
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all
  end

  def show
  end

  def new
    @product = Product.new
    session[:referer] = request.referer if request.referer == new_admin_import_url
  end

  def create
    @product = Product.new product_params
    if @product.save
      flash[:success] = "A new product has been added."
      redirect_back_or_to admin_products_path
    else
      flash.now[:danger] = "Error while processing data."
      render "new"
    end
  end

  def edit
  end

  def update
    if @product.update_attributes product_params
      flash[:success] = "Product's information has been updated."
      redirect_to admin_products_path
    else
      flash.now[:danger] = "Error while processing data."
      render "edit"
    end
  end

  def destroy
    @product.destroy
    flash[:success] = "Successfully remove a product."
    redirect_to admin_products_path
  end

  private

    def product_params
      params.require(:product).permit(:category_id, :name, :company, :price, :picture,
        :remote_picture_url, spec_attributes: [:cpu, :ram, :os, :storage, :screen_size, :vga, :battery])
    end

    def set_product
      @product = Product.find params[:id]
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    if params[:category_id].blank? && params[:company].blank?
      @products = Product.all
    elsif params[:category_id]
      category = Category.find params[:category_id]
      @products = category.products.where "company LIKE ?", "#{params[:company]}%"
    else
      @products = Product.where(company: params[:company])
    end
  end
  
  def show
    @categories = Category.all
    @product = Product.find(params[:id])
    @s = Spec.find_by(product: @product)
    session[:cart] = Hash.new(0) if session[:cart].nil?    
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def format_in_stock(product)
    if product.total.nil? || product.total.zero?
      "Out of Stock"
    else
      pluralize(product.total, "Item") + " In Stock"      
    end
  end
end

app/views/products/index.html.erb
<% provide :title, "Products" %>

<div class="form-wrapper product">
  <% unless @products.blank? %>
    <h2><%= @products[0].company %></h2>
  <% else %>
    <h2>No result was found!</h2>
  <% end %>
</div>
  <ul id="index">
  <% @products.each do |p| %>
    <%= image_tag p.picture_url(:small_thumb) %>
    <h3><%= link_to(p.name, product_path(p)) %></h3>
    <h4><%= format_in_stock(p)%></h4>
    <h4><%= number_to_currency(p.price)%> each</h4>
    <br />
  <% end %>
</ul>  
</div>

app/views/products/show.html.erb
<% provide :title, "Product's Spec" %>

<div class="form-wrapper product">
  <article id="product">
    <header>
      <h2 id="name"><%= @product.name %></h2>
    </header>
    <%= image_tag @product.picture_url(:big_thumb) %></div>
    <h4><strong>Category</strong></h4>
    <p><%= @product.category.name %></p>
    <h4><strong>Company</strong></h4>
    <p><%= @product.company %></p>
    <h4><strong>Price</strong></h4>
    <p><%= number_to_currency(@product.price) %></p>
    <h4><strong>Quantity</strong></h4>
    <p><%= format_in_stock(@product) %></p>
    <table>
      <%if @s != nil %>
        <h4><strong>Details</strong></h4>
        <tr>
          <th>Size:</th>
          <td><%= @s.screen_size %></td>
        </tr>
        <tr>
          <th>OS:</th>
          <td><%= @s.os %></td>
        </tr>
        <tr>
          <th>CPU:</th>
          <td><%= @s.cpu %></td>
        </tr>
        <tr>
          <th>RAM:</th>
          <td><%= @s.ram %></td>
        </tr>
        <tr>
          <th>VGA:</th>
          <td><%= @s.vga %></td>
        </tr>   
        <tr>
          <th>Storage:</th>
          <td><%= @s.storage %></td>
        </tr>
        <tr>
          <th>Battery:</th>
          <td><%= @s.battery %></td>
        </tr>     
      <%end%>     
    </table>    
    <%= form_tag order_items_path do %>        
      <%= hidden_field_tag :id, @product.id %>
      <ol class="breadcrumb">
        <li><%= link_to "Back", products_path+"?company="+@product.company %></li>       
        <li class="active"><%= submit_tag "Add to Cart" %></li>
      </ol>
    <% end %>     
  </article>
</div>