config/routes.rb
Entv::Application.routes.draw do
  root "static#index"
  resources :products, only: [:show, :index]
  resources :order_items, only: [:create, :index]
  resources :orders, only: [:create, :index, :new]
  delete 'order_items' => 'order_items#destroy', as: :delete_order_item
  patch 'order_items' => 'order_items#update', as: :update_order_item
  get "about" => "static#about", as: :about
  get "contact" => "static#contact", as: :contact

  devise_for :users
  devise_scope :user do
    get "sign_in" => "devise/sessions#new", as: :sign_in
    get "sign_out" => "devise/sessions#destroy", as: :sign_out
    get "sign_up" => "devise/registrations#new", as: :sign_up
    get "profile" => "devise/registrations#edit", as: :profile
    get "reset_password" => "devise/passwords#new", as: :reset_password
  end

  devise_for :admins
  devise_scope :admins do
    get "admins/sign_in" => "devise/sessions#new", as: :admin_sign_in
    get "admins/sign_out" => "devise/sessions#destroy", as: :admin_sign_out
  end
  
  namespace :admin do
    root "products#index"
    
    resources :products
    resources :orders, only: [:index, :show, :update]
    resources :users, only: [:index, :destroy]
    resources :categories, except: [:show, :destroy]
    resources :imports, except: [:edit, :update, :destroy]
  end
end

app/views/layouts/_content.html.erb
<div class="col-sm-10">
  <% flash.each do |key, value| %>
    <%= content_tag :div, value, class: "alert alert-#{key}" %>
  <% end %>
  <%= yield %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="navbar-header">
    <a class="navbar-brand" href="<%= root_path %>">
      <span>Cambo</span>
    </a>
  </div>

  <% unless admin_signed_in? %>
    <%= form_tag products_path, method: :get, class: "navbar-form pull-left" do %>
      <div class="form-group">
        <%= text_field_tag :company, nil, class: "form-control", placeholder: "Company" %>
      </div>
      <div class="form-group">
        <%= collection_select nil, nil, Category.all, :id, :name, {},
        class: "form-control", name: :category_id %>
      </div>
      <%= submit_tag "Search", class: "btn btn-default", name: nil %>
    <% end %>
  <% end %>

  <ul class="nav navbar-nav pull-right">
    <% if user_signed_in? %>
      <li><%= link_to "Hi, #{current_user.username}", profile_path %></li>
      <li><%= link_to "Order", orders_path %></li>
      <li><%= link_to "Cart", order_items_path %></li>
      <li><%= link_to "Sign Out", sign_out_path %></li>
    <% elsif admin_signed_in? %>
      <li><%= link_to "Admin, #{current_admin.username}", "" %></li>
      <li><%= link_to "Sign Out", admin_sign_out_path, data: { method: :delete } %></li>
    <% else %>
      <li><%= link_to "Sign In", sign_in_path %></li>
      <li><%= link_to "Sign Up", sign_up_path %></li>
      <li><%= link_to "Admin?", admin_sign_in_path %></li>
    <% end %>
  </ul>
</nav>

app/views/layouts/_sidebar.html.erb
<div class="col-sm-2">
  <% unless admin_signed_in? %>
    <div class="panel panel-default">
      <% @categories ||= Category.all %>
      <% @categories.each do |c| %>
        <div class="panel-heading">
        <h3 class="panel-title"><%= c.name %></h3>
        </div>
        <ul class="list-group">
          <% c.products.select("DISTINCT company").each do |c0| %>
            <li class="list-group-item">
              <%= link_to(c0.company, products_path(company: c0.company))  %>
            </li>
          <% end %>
        </ul>
      <% end %>
    </div>
  <% else %>
    <div class="panel panel-default">
      <ul id="admin-sidebar" class="nav nav-pills nav-stacked">
        <li><%= link_to "Category", admin_categories_path %></li>
        <li><%= link_to "Customer", admin_users_path %></li>
        <li><%= link_to "Import", admin_imports_path %></li>
        <li><%= link_to "Order", admin_orders_path %></li>
        <li><%= link_to "Product", admin_products_path %></li>
      </ul>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="description" content="Online electronics store. We sell variety of electronics device including smart phones, computers, laptops, headphone and more.">
  <meta name="keywords" content="Online store, Online electronics store, Computer, Smart Phone, Headphone, Electronic Device">
  <meta name="author" content="Hor Norin, Elit, Thai Visal, Buth Mathearo">
  <meta http-equiv="content-type" content="text/html;charset=UTF-8">
  <title><%= full_title yield(:title) %></title>
  <%= favicon_link_tag "favicon.ico" %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div id="header" class="row">
      <%= render "layouts/navbar" %>
    </div>
    <div class="row" id="content">
      <%= render "layouts/sidebar" %>
      <%= render "layouts/content" %>
    </div>
    <div class="row" id="footer">
      <ul>
        <li><a href="#">About</a></li>
        <li><a href="#">Contact</a></li>
      </ul>
    </div>
  </div>
</body>
</html>